name: Test
on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        otp: ["25.2"]
        elixir: ["1.15.6"]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: sudo apt-get update && sudo apt-get -y
      - run: mix deps.get
      - run: mix compile
      - run: mix test